
DELETE FROM COMMENTS CASCADE;
DELETE FROM BOOKING CASCADE;
DELETE FROM ITEMS CASCADE;
DELETE FROM ITEM_REQUEST CASCADE;
DELETE FROM USERS CASCADE;
ALTER TABLE ITEM_REQUEST ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE COMMENTS ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE BOOKING ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE USERS ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE ITEMS ALTER COLUMN ID RESTART WITH 1;